```
> python -m pytest -v tests/test_fit_transform_pytest.py
=============================== test session starts ===============================
platform win32 -- Python 3.10.7, pytest-7.2.0, pluggy-1.0.0 -- C:\Users\Nick\Documents\AVITO\python\instrumenty-testirovaniya-v-python\venv\Scripts\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\Nick\Documents\AVITO\python\instrumenty-testirovaniya-v-python    
plugins: cov-4.0.0
collected 6 items                                                                   

tests/test_fit_transform_pytest.py::test_fit_transform_1 PASSED              [ 16%] 
tests/test_fit_transform_pytest.py::test_fit_transform_2 PASSED              [ 33%] 
tests/test_fit_transform_pytest.py::test_fit_transform_3 PASSED              [ 50%]
tests/test_fit_transform_pytest.py::test_fit_transform_4 PASSED              [ 66%]
tests/test_fit_transform_pytest.py::test_fit_transform_exception_1 PASSED    [ 83%]
tests/test_fit_transform_pytest.py::test_fit_transform_exception_2 PASSED    [100%]

================================ 6 passed in 0.03s ================================
```